
[package]
name = "bushi"
version = "0.0.1"
published-at = "0xa06f691ab33cf37800ae1b79425efce85817b21cd50d6fc64a9bd4c5cacdc3c6"

[dependencies.Launchpad]
git = "https://github.com/Origin-Byte/nft-protocol.git"
subdir = "contracts/launchpad"
# mainnet
rev = "93f6cd0b8966354b1b00e7d798cbfddaa867a07b"

[dependencies.NftProtocol]
git = "https://github.com/Origin-Byte/nft-protocol.git"
subdir = "contracts/nft_protocol"
# mainnet
rev = "93f6cd0b8966354b1b00e7d798cbfddaa867a07b"

[dependencies.LiquidityLayerV1]
git = "https://github.com/Origin-Byte/nft-protocol.git"
subdir = "contracts/liquidity_layer_v1"
# mainnet
rev = "93f6cd0b8966354b1b00e7d798cbfddaa867a07b"

[addresses]
bushi =  "0x0"