
[package]
name = "bushi"
version = "0.0.4"
published-at = "0xced481707e5e0ba8004e2b505901dc00087fbe6fab57d8568e23a7c98322690f"

[dependencies.Launchpad]
git = "https://github.com/Origin-Byte/nft-protocol.git"
subdir = "contracts/launchpad"
# mainnet
rev = "1451825a7158833a0bf1d38a4bb8047a02d86650"

[dependencies.NftProtocol]
git = "https://github.com/Origin-Byte/nft-protocol.git"
subdir = "contracts/nft_protocol"
# mainnet
rev = "1451825a7158833a0bf1d38a4bb8047a02d86650"

[dependencies.LiquidityLayerV1]
git = "https://github.com/Origin-Byte/nft-protocol.git"
subdir = "contracts/liquidity_layer_v1"
# mainnet
rev = "1451825a7158833a0bf1d38a4bb8047a02d86650"

[addresses]
bushi =  "0x0"