[package]
name = "bushi"
version = "0.0.1"

[dependencies.Sui]
git = "https://github.com/MystenLabs/sui.git"
subdir = "crates/sui-framework/packages/sui-framework"
# testnet-0.33.0
rev = "c525ba6489261ff6db65e87bf9a3fdda0a6c7be3"

[dependencies.NftProtocol]
git = "https://github.com/Origin-Byte/nft-protocol.git"
subdir = "contracts/nft_protocol"
# testnet-0.33.0
rev = "d995e44d7f86df14921dbf683d171d6839fdd72a"

[dependencies.Launchpad]
git = "https://github.com/Origin-Byte/nft-protocol.git"
subdir = "contracts/launchpad"
# testnet-0.33.0
rev = "d995e44d7f86df14921dbf683d171d6839fdd72a"

[dependencies.Witness]
git = "https://github.com/Origin-Byte/nft-protocol.git"
subdir = "contracts/witness"
# testnet-0.33.0
rev = "d995e44d7f86df14921dbf683d171d6839fdd72a"

[dependencies.Request]
git = "https://github.com/Origin-Byte/nft-protocol.git"
subdir = "contracts/request"
# testnet-0.33.0
rev = "d995e44d7f86df14921dbf683d171d6839fdd72a"

[dependencies.Kiosk]
git = "https://github.com/Origin-Byte/nft-protocol.git"
subdir = "contracts/kiosk"
# testnet-0.33.0
rev = "d995e44d7f86df14921dbf683d171d6839fdd72a"

[addresses]
bushi =  "0x0"
