[package]
name = "bushi"
version = "0.0.1"

[dependencies.Sui]
git = "https://github.com/MystenLabs/sui.git"
subdir = "crates/sui-framework/packages/sui-framework"
# testnet-0.33.0
rev = "38c31cdd0f2ae3963d1e06f00c766cd7f90a7be6"

[dependencies.NftProtocol]
git = "https://github.com/Origin-Byte/nft-protocol"
subdir = "contracts/nft_protocol"
# testnet-0.33.0
rev = "afbf93bcd3146b4ede813fd8f89575f308be829f"

[dependencies.Permissions]
git = "https://github.com/Origin-Byte/nft-protocol"
subdir = "contracts/permissions"
# testnet-0.33.0
rev = "afbf93bcd3146b4ede813fd8f89575f308be829f"

[dependencies.Launchpad]
git = "https://github.com/Origin-Byte/nft-protocol"
subdir = "contracts/launchpad"
# testnet-0.33.0
rev = "afbf93bcd3146b4ede813fd8f89575f308be829f"

[dependencies.Request]
git = "https://github.com/Origin-Byte/nft-protocol"
subdir = "contracts/request"
# testnet-0.33.0
rev = "afbf93bcd3146b4ede813fd8f89575f308be829f"

[dependencies.Kiosk]
git = "https://github.com/Origin-Byte/nft-protocol"
subdir = "contracts/kiosk"
# testnet-0.33.0
rev = "afbf93bcd3146b4ede813fd8f89575f308be829f"

[dev-dependencies.Utils]
git = "https://github.com/Origin-Byte/nft-protocol"
subdir = "contracts/utils"
# testnet-0.33.0
rev = "afbf93bcd3146b4ede813fd8f89575f308be829f"

[addresses]
bushi =  "0x0"